name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  image_picker: ^0.8.7+5
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_sign_in: ^6.2.1
  firebase_auth: ^5.5.3
  geolocator: ^13.0.0        # ambil GPS koordinat
  geocoding: ^3.0.0 

  # Firebase
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding_bag.png
    - assets/images/empty_mascot.png
    - assets/images/Google_G_Logo.png
    - assets/images/splash-load.gif
    - assets/images/vector_permission.png
    - assets/images/vector_success.png
    - assets/images/vector_sihir.png
    - assets/images/vector_love.png
    - assets/images/vector_check.png
    - assets/images/vector_lostconnection.png

    - assets/images/maps.jpeg
    
    - assets/images/hotels/bali/abr/
    - assets/images/hotels/bali/lcr/
    - assets/images/hotels/bali/phr/

    - assets/images/hotels/bdg/ahr/
    - assets/images/hotels/bdg/pvl/

    - assets/images/hotels/jkt/cch/
    - assets/images/hotels/jkt/mgh/
    - assets/images/hotels/jkt/sch/

    - assets/images/hotels/jogja/bhi/
    - assets/images/hotels/jogja/jrr/
    - assets/images/hotels/jogja/mbs/
    - assets/images/hotels/jogja/tsh/

    - assets/images/kamars/bali/abr/cdr/
    - assets/images/kamars/bali/abr/obs/
    - assets/images/kamars/bali/lcr/cdr/
    - assets/images/kamars/bali/lcr/lgr/
    - assets/images/kamars/bali/lcr/rls/
    - assets/images/kamars/bali/phr/hcr/
    - assets/images/kamars/bali/phr/sps/

    - assets/images/kamars/bdg/ahr/agr/
    - assets/images/kamars/bdg/ahr/phs/
    - assets/images/kamars/bdg/pvl/pcr/
    - assets/images/kamars/bdg/pvl/vvr/

    - assets/images/kamars/jkt/cch/ccr/
    - assets/images/kamars/jkt/cch/cdr/
    - assets/images/kamars/jkt/mgh/gms/
    - assets/images/kamars/jkt/mgh/mbr/
    - assets/images/kamars/jkt/mgh/usr/
    - assets/images/kamars/jkt/sch/cvr/
    - assets/images/kamars/jkt/sch/sdr/

    - assets/images/kamars/jogja/bhi/hcr/
    - assets/images/kamars/jogja/bhi/rhs/
    - assets/images/kamars/jogja/bhi/tvr/
    - assets/images/kamars/jogja/jrr/jcr/
    - assets/images/kamars/jogja/jrr/rgr/
    - assets/images/kamars/jogja/mbs/mcr/
    - assets/images/kamars/jogja/mbs/ss/
    - assets/images/kamars/jogja/tsh/jhs/
    - assets/images/kamars/jogja/tsh/scr/

    - assets/images/app_icon.png
